apiVersion: v1
kind: Secret
metadata:
  name: {{ template "discourse.fullname" . }}
  labels: {{- include "discourse.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.discoursePassword }}
  discourse-password: {{ .Values.discoursePassword | b64enc | quote }}
  {{- else }}
  discourse-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}

  {{- if .Values.postgresql.postgresqlPassword }}
  discourse-postgresql-password: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  {{- else }}
  discourse-postgresql-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}

  {{- if .Values.postgresql.postgresqlPostgresPassword }}
  postgresql-root-password: {{ .Values.postgresql.postgresqlPostgresPassword | b64enc | quote }}
  {{- else }}
  postgresql-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}

  {{- if .Values.postgresql.postgresqlPassword }}
  postgresql-client-create-database-password: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  {{- else }}
  postgresql-client-create-database-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}

  {{- if .Values.redis.password }}
  redis-password: {{ .Values.redis.password | b64enc | quote }}
  {{- else }}
  redis-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
